---
title: "Untitled"
format: html
editor: visual
---
```{r}
# Load required packages
pacman::p_load(brms, MCMCglmm, metafor, metadat, tidyverse, dplyr, tidyr, purrr, stringr, readr, readxl, lubridate, magrittr, janitor, flextable, kableExtra, geosphere)

dat <- dat.maire2019$dat
dmat <- dat.maire2019$dmat
dat
dmat[1:5,1:5]
```
```{r}

# fit model allowing for spatial correlation ----
## metafor ----

res1 <- rma.mv(s1, vars1, random = ~ site_station | const, struct="SPGAU",
               data=dat, dist=list(dmat), control=list(rho.init=10))
res1

## brms ----
hist(dmat)
rho <- 15 # Set the spatial scale parameter rho, based on the value estimated from the metafor model

# Create a spatial correlation matrix using a Gaussian kernel:
# each element is exp(-d^2 / rho^2), where d is the distance between two locations
# and rho is the spatial scale parameter
cor_mat <- exp(-(dat.maire2019$dmat^2) / rho^2)

A <- cor_mat

# Ensure the correlation matrix is positive definite, which is required by brms - nearPD() finds the nearest positive definite matrix to avoid errors
# If I do not run this code, I get "Error: Within-group covariance matrices must be positive definite." in prior_ma1
A <- as.matrix(nearPD(A, corr = TRUE)$mat) 

# Set the row and column names of the matrix to match the site_station IDs in the dataset
# Correct alignment of correlation matrix with observations
rownames(cor_mat) <- colnames(cor_mat) <- dat$site_station

dat$yi <- dat$s1
dat$sei <- sqrt(dat$vars1)
hist()
formula_1 <- bf(yi | se(sei) ~ 1 + (1 | gr(site_station, cov = A)))

prior_ma1 <- get_prior(
  formula = formula_1,
  data = dat,
  data2 = list(A = A),
  family = gaussian()
)

fit_brm1 <- brm(
  formula_1,
  data = dat,
  data2 = list(A = A),
  chains = 2, 
  iter = 3000, 
  warmup = 2000,
  prior = prior_ma1
)

summary(fit_brm1)

# add random effects for sites and stations within sites ----
## metafor ----
res2 <- rma.mv(s1, vars1, random = list(~ 1 | site/station, ~ site_station | const), struct="SPGAU",
               data=dat, dist=list(dmat), control=list(rho.init=10))
res2

## brms ----
rho <- 12 # referred to the metafor rho
cor_mat <- exp(-(dat.maire2019$dmat^2) / rho^2)
A <- cor_mat
A <- as.matrix(nearPD(A, corr = TRUE)$mat) #If I do not run this code, I get "Error: Within-group covariance matrices must be positive definite." in prior_ma2
rownames(cor_mat) <- colnames(cor_mat) <- dat$site_station


formula_2 <- bf(yi | se(sei) ~ 1 +  (1 | site/station) + (1 | gr(site_station, cov = A)))

prior_ma2 <- get_prior(
  formula = formula_2,
  data = dat,
  data2 = list(A = A),
  family = gaussian()
)

fit_brm2 <- brm(
  formula_2,
  data = dat,
  data2 = list(A = A),
  chains = 2, 
  iter = 5000, 
  warmup = 4000,
  prior = prior_ma2,
  control = list(adapt_delta = 0.95)
)

summary(fit_brm2)

```


